spring:
  datasource:
    url: jdbc:postgresql://localhost:54320/perfdb
    username: perfuser
    password: perfpassword
    hikari:
      maximum-pool-size: 200
      minimum-idle: 100
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:54320/perfdb
    user: perfuser
    password: perfpassword

logging:
  level:
    org.flywaydb: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

clients:
  inventory:
    url: http://localhost:8081
  payment:
    url: http://localhost:8081
