spring:
  datasource:
    url: jdbc:postgresql://localhost:54320/perfdb
    username: perfuser
    password: perfpassword
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10

clients:
  inventory:
    url: http://localhost:8081
  payment:
    url: http://localhost:8081
