services:
  postgres-test:
    image: postgres:17-alpine
    container_name: postgres-test
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb